baseURL = "https://ricky-hu.com/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Ricky Hu"

defaultContentLanguage = "en"
# language code ["en", "zh-TW", "fr", "pl", ...]
languageCode = "en"
# language name ["English", "繁體中文", "Français", "Polski", ...]
languageName = "English"

hasCJKLanguage = false

# Author config
[author]
  name = "Ricky Hu"
  email = "ricky9667@gmail.com"
  link = "https://ricky-hu.com/"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = "<i class='fa-solid fa-newspaper'></i>"
    post = ""
    name = " Posts "
    url = "/posts/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = "<i class='fa-solid fa-tag'></i>"
    post = ""
    name = " Tags "
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = "<i class='fa-solid fa-list'></i>"
    post = ""
    name = " Categories "
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "about"
    pre = "<i class='fa-solid fa-address-card'></i>"
    post = ""
    name = " About "
    url = "/about/"
    title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = ""
  # LoveIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # LoveIt NEW | 0.2.0 date format
  dateFormat = "2006-01-02"
  # website title for Open Graph and Twitter Cards
  title = "Ricky's Blog"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "This is Ricky Hu's Blog."
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]

  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "https://cdn-icons-png.flaticon.com/512/6062/6062646.png"
      # title name
      name = "Ricky Hu"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = " "
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

  # LoveIt NEW | 0.2.0 App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "My cool site"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = "https://cdn-icons-png.flaticon.com/512/6062/6062646.png"
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"

  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = "ricky9667@gmail.com"
      # URL of avatar shown in home page
      avatarURL = ""
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Ricky Hu"
      # subtitle shown in home page (HTML format is supported)
      subtitle = "Learn more to contribute more."
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = "" 
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Social config about the author
  [params.social]
    GitHub = "ricky9667" 
    Linkedin = "ricky9667"
    Twitter = "ricky9667"
    Instagram = "ricky_hu_0110"
    Facebook = "ricky.hu.0110"
    Telegram = "ricky9667"
    Youtubechannel = ""
    RSS = false
